# Generated by Django 4.2.5 on 2023-09-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='solve1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve2',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve3',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve4',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve5',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve_avg',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve_best',
            field=models.CharField(max_length=15),
        ),
    ]
