# Generated by Django 4.2.5 on 2023-09-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_solve1_alter_participant_solve2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='solve1',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve2',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve3',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve4',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve5',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve_avg',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='participant',
            name='solve_best',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
