# Generated by Django 4.2.5 on 2023-09-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_solve1_alter_participant_solve2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='competetion',
            field=models.CharField(default='-', max_length=55),
            preserve_default=False,
        ),
    ]
